export const Addwhishlist ='Addwhishlist';
export const ORDERED_BOOKS ='ORDERED_BOOKS';
export const SET_BOOKS ='SET_BOOKS';
export const SEARCH_ERROR ='SEARCH_ERROR';
export const SEARCH_VALUE='SEARCH_VALUE';
export const FILTER_HANDLER='FILTER_HANDLER';
export const BOOKS_LIST ='BOOKS_LIST';
export const ORDER_BOOKS_SUCCESS='ORDER_BOOKS_SUCCESS';
export const ORDER_BOOKS_FAILURE='ORDER_BOOKS_FAILURE';
export const ORDER_BOOKS_START ='ORDER_BOOKS_START';
export const CHECKOUT_BOOK ='CHECKOUT_BOOK';
export const REMOVEWISHLIST='REMOVEWISHLIST'
export const ORDERCHECKOUT_INIT ='ORDERCHECKOUT_INIT';
export const FETCH_ORDERS_START ='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT='AUTH_LOGOUT';
export const CHECKOUT_REMOVE ='CHECKOUT_REMOVE';
export const ORDER_CANCEL ='ORDER_CANCEL';
export const ORDER_INIT = 'ORDER_INIT';